<?php
// $Id$

function docuwalk_init() {
  drupal_add_css(drupal_get_path('module', 'docuwalk') . '/docuwalk.css');
}

function docuwalk_views_api() {
  return array(
    'api' => 2.0,
    'path' => drupal_get_path('module', 'docuwalk') .'/views',
  );
}

/**
 * Implementation of hook_autoload_info().
 */
function docuwalk_autoload_info() {
  return array(
    'DocuWalkTaskResource' => array(
      'file' => 'includes/DocuWalkTaskResource.php',
    ),
    'DocuWalkSolutionResource' => array(
      'file' => 'includes/DocuWalkSolutionResource.php',
    ),
    'DocuWalkTextResource' => array(
      'file' => 'includes/DocuWalkTextResource.php',
    ),
    'DocuWalkPictureResource' => array(
      'file' => 'includes/DocuWalkPictureResource.php',
    ),
  );
}

/**
 * Implementation of hook_service_resource().
 */
function docuwalk_service_resource() {
  $res = array(
    'docuwalk-task' => ServicesOop::definitionFromClass('DocuWalkTaskResource'),
    'docuwalk-solution' => ServicesOop::definitionFromClass('DocuWalkSolutionResource'),
    'docuwalk-text' => ServicesOop::definitionFromClass('DocuWalkTextResource'),
    'docuwalk-picture' => ServicesOop::definitionFromClass('DocuWalkPictureResource'),
  );
  return $res;
}

/**
 * Implementation of hook_services_contexts().
 */
function docuwalk_services_contexts() {
  return array(
    'docuwalk' => array(
      'title' => 'DocuWalk API',
      'server' => 'rest_server',
      'path' => 'api',
      'authentication' => 'services_oauth',
      'authentication_settings' => array(
        'oauth_context' => 'docuwalk',
      ),
      'resources' => array(
        'docuwalk-task' => array(
          'operations' => array(
            'create' => array(
              'enabled' => TRUE,
            ),
            'retrieve' => array(
              'enabled' => TRUE,
            ),
            'update' => array(
              'enabled' => TRUE,
            ),
            'delete' => array(
              'enabled' => TRUE,
            ),
            'index' => array(
              'enabled' => TRUE,
            ),
          ),
        ),
        'docuwalk-solution' => array(
          'operations' => array(
            'create' => array(
              'enabled' => TRUE,
            ),
            'retrieve' => array(
              'enabled' => TRUE,
            ),
            'update' => array(
              'enabled' => TRUE,
            ),
            'delete' => array(
              'enabled' => TRUE,
            ),
            'index' => array(
              'enabled' => TRUE,
            ),
          ),
          'targeted actions' => array(
            'add-waypoint' => array(
              'enabled' => TRUE,
            ),
          ),
        ),
        'docuwalk-text' => array(
          'operations' => array(
            'create' => array(
              'enabled' => TRUE,
            ),
            'retrieve' => array(
              'enabled' => TRUE,
            ),
            'update' => array(
              'enabled' => TRUE,
            ),
            'delete' => array(
              'enabled' => TRUE,
            ),
            'index' => array(
              'enabled' => TRUE,
            ),
          ),
        ),
      ),
    ),
  );
}